import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

import { Toaster } from '@/components/ui/toaster'
import { Navbar } from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <div className='relative flex min-h-screen flex-col'>
          <Navbar />
          <div className='flex-1'>{children}</div>
          <Toaster />
        </div>
      </body>
    </html>
  )
}
